let
    Source = Excel.Workbook(File.Contents("C:\Users\Administrator\Downloads\RawData-Quipt--20250101-20251231.xlsx"), null, true),
    Data_Sheet = Source{[Item="Data",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"unqid", type text}, {"LastDoctorCallCount", Int64.Type}, {"LastDoctorDisposition", type text}, {"LastDoctorAttemptDate", type datetime}, {"LastPatientCallCount", Int64.Type}, {"LastPatientDisposition", type text}, {"LastPatientAttemptDate", type datetime}, {"LastMedicalNoteOnlyCallCount", Int64.Type}, {"LastMedicalNoteOnlyDisposition", type any}, {"LastMedicalNoteOnlyAttemptDate", type any}, {"LastMedicalNotePatientCallCount", Int64.Type}, {"LastMedicalNotePatientCallDisposition", type any}, {"LastMedicalNotePatientCallAttemptDate", type any}, {"LastReworkCallCount", Int64.Type}, {"LastReworkDisposition", type any}, {"LastReworkAttemptDate", type any}, {"DNC", type text}, {"DNF ", type text}, {"UseEmail", type text}, {"POC", type text}, {"UseClientPhoneFaxOnly", type text}, {"CallFirst", type text}, {"UseEDocumentService", type text}, {"EDocumentServiceName", type text}, {"Email", type any}, {"PhoneNumbers", type number}, {"FaxNumbers", type number}, {"SalesRep", type text}, {"LastFaxDate", type datetime}, {"LastFaxResult", type text}, {"LastFaxCampaign", type text}, {"LastTouchedDate", type date}, {"DaysSinceWorked", Int64.Type}, {"Recd_Date", type date}, {"Client", type text}, {"SubClient", type text}, {"FirstName", type text}, {"LastName", type text}, {"ProductCode", type text}, {"AilmentType", type text}, {"Address", type text}, {"Address2", type any}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"HomePhone", Int64.Type}, {"DateOfBirth", type date}, {"PatientFollowUpDate", type date}, {"DoctorNpi", Int64.Type}, {"DoctorFirstName", type text}, {"DoctorLastName", type text}, {"DoctorAddress", type text}, {"DoctorAddress2", type text}, {"DoctorCity", type text}, {"DoctorState", type text}, {"DoctorZip", Int64.Type}, {"DoctorPhone", Int64.Type}, {"DoctorFax", Int64.Type}, {"DoctorUpdated", type text}, {"PreviousStatus", type text}, {"PreviousSubStatus", type text}, {"Status", type text}, {"SubStatus", type text}, {"StatusDate", type datetime}, {"pmcnumber", type text}, {"dnf", type text}, {"Chart_Id", Int64.Type}, {"Age", type any}, {"MI", type any}, {"File_Name", type text}, {"Entry_Date", type date}, {"Upload_date", type date}, {"Rx Date", type date}, {"Medical Records Date", type date}, {"Verification Date", type any}, {"Medi_Adv_Carrier", type any}, {"Medi_Adv_Mem_ID", type any}, {"Medi_Adv_Carrier_Phone", type any}, {"Medi_Adv_Address", type any}, {"Medi_Adv_Address2", type any}, {"Medi_Adv_City", type any}, {"Medi_Adv_State", type any}, {"Medi_Adv_Zip", type any}, {"In_Net", type any}, {"Deductible", type any}, {"co_pay_per", type any}, {"co_pay_total", type any}, {"OOP_Cost", type any}, {"Medi_Sup_Ins_Name", type any}, {"Medi_Sup_Ins_Mem_ID", type any}, {"Medi_Sup_Ins_Phone", type any}, {"Medi_Sup_Ins_Address", type any}, {"Medi_Sup_Ins_Address2", type any}, {"Medi_Sup_Ins_City", type any}, {"Medi_Sup_Ins_State", type any}, {"Medi_Sup_Ins_Zip", type any}, {"ss_status", type text}, {"ins_status", type text}, {"pecos_status", type text}, {"Custom1", Int64.Type}, {"Custom2", type text}, {"Custom3", type text}, {"Custom4", type text}, {"Custom5", type text}, {"Custom6", type text}, {"Custom7", type text}, {"Custom8", type text}, {"Custom9", type number}, {"Custom10", type date}, {"Custom11", type text}, {"Custom12", type text}, {"Custom13", type text}, {"Custom14", type any}, {"Custom15", type any}, {"SourceCode", type any}, {"PCN", type any}, {"BIN", type any}, {"PrescriptionGroup", type text}, {"ClientName", type text}, {"FollowUpDate", type any}, {"SameSimilarDate", type any}, {"SameSimilarCompany", type any}, {"SameSimilarHCPCS", type any}, {"RxChaseFaxStatus", type text}, {"RxChaseFaxSuccess", Int64.Type}, {"RxChaseFaxFail", Int64.Type}, {"RxChaseFaxLastAttempt", type datetime}, {"Medications", type text}, {"BrandName", type text}, {"BtInstance", type text}, {"AgingReceivedDays", Int64.Type}, {"AgingEntryDays", Int64.Type}, {"Days Grouping", type text}}),
    #"1. SORTED BTInstance col (ASC), unqid col (DEC)" = Table.Sort(#"Changed Type",{{"BtInstance", Order.Ascending}, {"unqid", Order.Descending}}),
    #"2. CHANGED type" = Table.TransformColumnTypes(#"1. SORTED BTInstance col (ASC), unqid col (DEC)",{{"LastTouchedDate", type date}, {"Recd_Date", type date}, {"Custom10", type date}, {"Chart_Id", Int64.Type}}),
    #"3. REMOVED Prev Status col & Prev SubStatus col" = Table.RemoveColumns(#"2. CHANGED type",{"PreviousStatus", "PreviousSubStatus"})
in
    #"3. REMOVED Prev Status col & Prev SubStatus col"