let
    Source = Excel.Workbook(File.Contents("C:\Users\Administrator\Downloads\QUIPT SLA Report.xlsx"), null, true),
    #"SLA Report_Sheet" = Source{[Item="SLA Report",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"SLA Report_Sheet", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", type text}, {"3 or less", Int64.Type}, {"4 to 7", Int64.Type}, {"7 or less", Int64.Type}, {"7 to 10", Int64.Type}, {"11 to 14", Int64.Type}, {"15 to 21", Int64.Type}, {"22 to 30", Int64.Type}, {"31 to 60", Int64.Type}, {"61 to 90", Int64.Type}, {"91 to 120", Int64.Type}, {"121 to 180", Int64.Type}, {"181 plus", Int64.Type}, {"Column14", type logical}}),
    #"1. REMOVED Column14" = Table.RemoveColumns(#"Changed Type",{"Column14"}),
    #"2. FILTERED Total" = Table.SelectRows(#"1. REMOVED Column14", each ([#""] <> "Total")),
    #"3. REPLACED 0 with NULL" = Table.ReplaceValue(#"2. FILTERED Total",0,null,Replacer.ReplaceValue,{"3 or less", "4 to 7", "7 or less", "7 to 10", "11 to 14", "15 to 21", "22 to 30", "31 to 60", "61 to 90", "91 to 120", "121 to 180", "181 plus"}),
    #"4. RENAMED STATUS col" = Table.RenameColumns(#"3. REPLACED 0 with NULL",{{"", "STATUS"}})
in
    #"4. RENAMED STATUS col"