QUIPT Prod Camp Files

let
    Source = Folder.Files("C:\Users\Administrator\Downloads\QUIPT PROD CAMP FILES"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"CallID", Int64.Type}, {"Campaign", type text}, {"Direction", type text}, {"From", Int64.Type}, {"To", Int64.Type}, {"AgentID", Int64.Type}, {"AgentEmail", type text}, {"StartTime", type datetime}, {"Duration", Int64.Type}, {"Result", type text}, {"LeadID", Int64.Type}, {"ExternalLeadID", type text}, {"PubID", type any}, {"SubID", type any}, {"TalkTime", Int64.Type}, {"WrapUpDuration", Int64.Type}, {"CompletedDate", type datetime}}),
    #"1. REMOVED Source.Name col" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
    #"2. FILTERED OUT Null AgentEmail" = Table.SelectRows(#"1. REMOVED Source.Name col", each [AgentEmail] <> null and [AgentEmail] <> "")
in
    #"2. FILTERED OUT Null AgentEmail"

---------------------------------------------------------------------------------------------------------------------------------------

Raw Data

let
    Source = Excel.Workbook(File.Contents("G:\Shared drives\Ramel\Tusoy_Reports\Weekly Quipt Raw Data.xlsx"), null, true),
    #"Expanded Data" = Table.ExpandTableColumn(Source, "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131"}, {"Data.Column1", "Data.Column2", "Data.Column3", "Data.Column4", "Data.Column5", "Data.Column6", "Data.Column7", "Data.Column8", "Data.Column9", "Data.Column10", "Data.Column11", "Data.Column12", "Data.Column13", "Data.Column14", "Data.Column15", "Data.Column16", "Data.Column17", "Data.Column18", "Data.Column19", "Data.Column20", "Data.Column21", "Data.Column22", "Data.Column23", "Data.Column24", "Data.Column25", "Data.Column26", "Data.Column27", "Data.Column28", "Data.Column29", "Data.Column30", "Data.Column31", "Data.Column32", "Data.Column33", "Data.Column34", "Data.Column35", "Data.Column36", "Data.Column37", "Data.Column38", "Data.Column39", "Data.Column40", "Data.Column41", "Data.Column42", "Data.Column43", "Data.Column44", "Data.Column45", "Data.Column46", "Data.Column47", "Data.Column48", "Data.Column49", "Data.Column50", "Data.Column51", "Data.Column52", "Data.Column53", "Data.Column54", "Data.Column55", "Data.Column56", "Data.Column57", "Data.Column58", "Data.Column59", "Data.Column60", "Data.Column61", "Data.Column62", "Data.Column63", "Data.Column64", "Data.Column65", "Data.Column66", "Data.Column67", "Data.Column68", "Data.Column69", "Data.Column70", "Data.Column71", "Data.Column72", "Data.Column73", "Data.Column74", "Data.Column75", "Data.Column76", "Data.Column77", "Data.Column78", "Data.Column79", "Data.Column80", "Data.Column81", "Data.Column82", "Data.Column83", "Data.Column84", "Data.Column85", "Data.Column86", "Data.Column87", "Data.Column88", "Data.Column89", "Data.Column90", "Data.Column91", "Data.Column92", "Data.Column93", "Data.Column94", "Data.Column95", "Data.Column96", "Data.Column97", "Data.Column98", "Data.Column99", "Data.Column100", "Data.Column101", "Data.Column102", "Data.Column103", "Data.Column104", "Data.Column105", "Data.Column106", "Data.Column107", "Data.Column108", "Data.Column109", "Data.Column110", "Data.Column111", "Data.Column112", "Data.Column113", "Data.Column114", "Data.Column115", "Data.Column116", "Data.Column117", "Data.Column118", "Data.Column119", "Data.Column120", "Data.Column121", "Data.Column122", "Data.Column123", "Data.Column124", "Data.Column125", "Data.Column126", "Data.Column127", "Data.Column128", "Data.Column129", "Data.Column130", "Data.Column131"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Data",{"Name"}),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Columns", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"unqid", type text}, {"LastDoctorCallCount", Int64.Type}, {"LastDoctorDisposition", type text}, {"LastDoctorAttemptDate", type datetime}, {"LastPatientCallCount", Int64.Type}, {"LastPatientDisposition", type text}, {"LastPatientAttemptDate", type datetime}, {"LastMedicalNoteOnlyCallCount", Int64.Type}, {"LastMedicalNoteOnlyDisposition", type any}, {"LastMedicalNoteOnlyAttemptDate", type any}, {"LastMedicalNotePatientCallCount", Int64.Type}, {"LastMedicalNotePatientCallDisposition", type any}, {"LastMedicalNotePatientCallAttemptDate", type any}, {"LastReworkCallCount", Int64.Type}, {"LastReworkDisposition", type any}, {"LastReworkAttemptDate", type any}, {"DNC", type text}, {"DNF", type text}, {"UseEmail", type text}, {"POC", type text}, {"UseClientPhoneFaxOnly", type text}, {"CallFirst", type text}, {"UseEDocumentService", type text}, {"EDocumentServiceName", type text}, {"Email", type any}, {"PhoneNumbers", type number}, {"FaxNumbers", type number}, {"SalesRep", type text}, {"LastFaxDate", type datetime}, {"LastFaxResult", type text}, {"LastFaxCampaign", type text}, {"LastTouchedDate", type date}, {"DaysSinceWorked", Int64.Type}, {"Recd_Date", type date}, {"Client", type text}, {"SubClient", type text}, {"FirstName", type text}, {"LastName", type text}, {"ProductCode", type text}, {"AilmentType", type text}, {"Address", type text}, {"Address2", type any}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"HomePhone", Int64.Type}, {"DateOfBirth", type date}, {"PatientFollowUpDate", type date}, {"DoctorNpi", Int64.Type}, {"DoctorFirstName", type text}, {"DoctorLastName", type text}, {"DoctorAddress", type text}, {"DoctorAddress2", type text}, {"DoctorCity", type text}, {"DoctorState", type text}, {"DoctorZip", Int64.Type}, {"DoctorPhone", Int64.Type}, {"DoctorFax", Int64.Type}, {"DoctorUpdated", type text}, {"Status", type text}, {"SubStatus", type text}, {"StatusDate", type datetime}, {"pmcnumber", type text}, {"dnf", type text}, {"Chart_Id", Int64.Type}, {"Age", type any}, {"MI", type any}, {"File_Name", type text}, {"Entry_Date", type date}, {"Upload_date", type date}, {"Rx Date", type date}, {"Medical Records Date", type date}, {"Verification Date", type any}, {"Medi_Adv_Carrier", type any}, {"Medi_Adv_Mem_ID", type any}, {"Medi_Adv_Carrier_Phone", type any}, {"Medi_Adv_Address", type any}, {"Medi_Adv_Address2", type any}, {"Medi_Adv_City", type any}, {"Medi_Adv_State", type any}, {"Medi_Adv_Zip", type any}, {"In_Net", type any}, {"Deductible", type any}, {"co_pay_per", type any}, {"co_pay_total", type any}, {"OOP_Cost", type any}, {"Medi_Sup_Ins_Name", type any}, {"Medi_Sup_Ins_Mem_ID", type any}, {"Medi_Sup_Ins_Phone", type any}, {"Medi_Sup_Ins_Address", type any}, {"Medi_Sup_Ins_Address2", type any}, {"Medi_Sup_Ins_City", type any}, {"Medi_Sup_Ins_State", type any}, {"Medi_Sup_Ins_Zip", type any}, {"ss_status", type text}, {"ins_status", type text}, {"pecos_status", type text}, {"Custom1", Int64.Type}, {"Custom2", type text}, {"Custom3", type text}, {"Custom4", type text}, {"Custom5", type text}, {"Custom6", type text}, {"Custom7", type text}, {"Custom8", type text}, {"Custom9", type number}, {"Custom10", type date}, {"Custom11", type text}, {"Custom12", type text}, {"Custom13", type text}, {"Custom14", type text}, {"Custom15", type any}, {"SourceCode", type any}, {"PCN", type any}, {"BIN", type any}, {"PrescriptionGroup", type any}, {"ClientName", type text}, {"FollowUpDate", type any}, {"SameSimilarDate", type any}, {"SameSimilarCompany", type any}, {"SameSimilarHCPCS", type any}, {"RxChaseFaxStatus", type text}, {"RxChaseFaxSuccess", Int64.Type}, {"RxChaseFaxFail", Int64.Type}, {"RxChaseFaxLastAttempt", type datetime}, {"Medications", type text}, {"BrandName", type text}, {"BtInstance", type text}, {"AgingReceivedDays", Int64.Type}, {"AgingEntryDays", Int64.Type}, {"Days Grouping", type text}, {"Data", type text}, {"Sheet", type text}, {"false", type logical}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"dnf", "dnf.1"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"unqid", "SubStatus", "Days Grouping"})
in
    #"Removed Other Columns"