STL StopDash

let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"SNAPSHOT_DATE", type datetime}, {"NICKNAME", type text}, {"SOKEY", Int64.Type}, {"PATIENTID", Int64.Type}, {"PT_OPSREGION", type text}, {"PT_BRANCHNAME", type text}, {"SO_BRANCHNAME", type text}, {"SOSTATUS", type text}, {"Auth Leader", type text}, {"REGIONALEXCLUSIONS", type text}, {"MANUALHOLDREASON", type text}, {"SERVICEDT", type datetime}, {"NEXTBILLDATE", type datetime}, {"NEXTBILLDATE_FLAG", type text}, {"NEXTBILLPD", Int64.Type}, {"NEXTBILLDT_AGING", type text}, {"SO_CLASSIFICATION", type text}, {"PROCCODE", type text}, {"ITEMGROUP", type text}, {"BILLQTY", Int64.Type}, {"CHARGEAMT", type number}, {"ALLOWAMT", type number}, {"EXTALLOWAMT", type number}, {"WIPSTATENAME", type text}, {"DAYSINWIP", Int64.Type}, {"WIPASSIGNEDTO", type text}, {"WIPNEEDDT", type datetime}, {"INVOICES_ON_HOLD", Int64.Type}, {"INVOICEONHOLD", type text}, {"PAYORNAME", type text}, {"POLICYNBR", type any}, {"STOPPEDBILLING", type text}, {"PAR_WORKFLOW", type text}, {"PARDATE_ACTIONTAKEN", type datetime}, {"U_PARKEY", type number}, {"PARNUMBER", type any}, {"PAR_DESCRIPTION", type text}, {"INITIAL_DATE", type datetime}, {"EXP_DATE", type datetime}, {"PAR_LOGDT", type datetime}, {"PAR_LOGGED_BY", type text}, {"STOPREASON", type text}, {"ORDERSTOP_CHANGEDT", type datetime}, {"SOSTOPDATE", type datetime}, {"STOP_AGING", type text}, {"HOLD_STOP_GROUP", type text}, {"STOP_GROUPING", type text}, {"ACCOUNTNBR", type any}, {"DATEOFDISCHARGE", type datetime}, {"DAYSFROM_NEXTBILLDATE", Int64.Type}, {"DAYSFROM_SERVICEDATE", Int64.Type}, {"SOACTUALDELIVERYDATE", type datetime}, {"SOCONFIRMDATE", type datetime}, {"SOCREATEDATE", type datetime}, {"SOCREATEDBY", type text}, {"DONOTCALL_FLAG", type logical}, {"DONOTFAX_FLAG", type logical}, {"GOSCRIPTSENROLLED_FLAG", type logical}, {"INTERNALCONTACTNAME", type text}, {"ORDERINGDOCTOR", type text}, {"NPI", Int64.Type}, {"DOD_FLAG", type logical}, {"PUEXSTATNAME", type text}, {"PUEXREASONNAME", type text}, {"PUEXTYPENAME", type text}, {"FINALBILLDT", type datetime}, {"SODTLKEY", Int64.Type}, {"SODTLSTATUS", type text}, {"U_SODTLKEY", type number}, {"Wip Aging Bucket", type text}, {"Region Lead", type text}, {"GoScripts", type text}, {"Parachute", type text}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"PARDATE_ACTIONTAKEN", type date}}),
    #"Sorted ParDate_ActionTaken" = Table.Sort(#"Changed Type1",{{"PARDATE_ACTIONTAKEN", Order.Ascending}, {"ITEMGROUP", Order.Descending}}),
    #"Filtered Rows" = Table.SelectRows(#"Sorted ParDate_ActionTaken", each ([NICKNAME] = "StLukesHS")),
    Custom1 = #"Filtered Rows",
    #"Filtered Rows2" = Table.SelectRows(Custom1, each ([FutureDated] = "")),
    #"Reordered Columns" = Table.ReorderColumns(#"Filtered Rows2",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_OPSREGION", "PT_BRANCHNAME", "SO_BRANCHNAME", "SOSTATUS", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "SERVICEDT", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "ITEMGROUP", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "WIPSTATENAME", "DAYSINWIP", "WIPASSIGNEDTO", "WIPNEEDDT", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PAR_WORKFLOW", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_NEXTBILLDATE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "NPI", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "Region Lead", "GoScripts", "Parachute", "SOKEY", "PAYORNAME", "POLICYNBR"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "No Retro Payer", each ""),
    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_OPSREGION", "PT_BRANCHNAME", "SO_BRANCHNAME", "SOSTATUS", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "SERVICEDT", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "WIPSTATENAME", "DAYSINWIP", "WIPASSIGNEDTO", "WIPNEEDDT", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_NEXTBILLDATE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "NPI", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "Region Lead", "GoScripts", "Parachute", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW"}),
    #"Added Custom1" = Table.AddColumn(#"Reordered Columns1", "File", each "Stopped Dash"),
    #"Reordered Columns2" = Table.ReorderColumns(#"Added Custom1",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_OPSREGION", "PT_BRANCHNAME", "SO_BRANCHNAME", "SOSTATUS", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "SERVICEDT", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "WIPSTATENAME", "DAYSINWIP", "WIPASSIGNEDTO", "WIPNEEDDT", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_NEXTBILLDATE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "Region Lead", "GoScripts", "Parachute", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Reordered Columns2",{{"WIPNEEDDT", type date}}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Changed Type2",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_OPSREGION", "PT_BRANCHNAME", "SO_BRANCHNAME", "SOSTATUS", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "SERVICEDT", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "WIPSTATENAME", "DAYSINWIP", "WIPASSIGNEDTO", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_NEXTBILLDATE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "Region Lead", "GoScripts", "Parachute", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT"}),
    #"Added Custom2" = Table.AddColumn(#"Reordered Columns3", "Workflow Flag", each "Stopped Dash"),
    #"Reordered Columns4" = Table.ReorderColumns(#"Added Custom2",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "SOSTATUS", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "SERVICEDT", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "WIPSTATENAME", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_NEXTBILLDATE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "GoScripts", "Parachute", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "Workflow Flag", "WIPASSIGNEDTO", "PT_OPSREGION", "Region Lead"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns4",{{"SERVICEDT", type date}}),
    #"Reordered Columns5" = Table.ReorderColumns(#"Changed Type3",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "SOSTATUS", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "WIPSTATENAME", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_NEXTBILLDATE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "GoScripts", "Parachute", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "Workflow Flag", "WIPASSIGNEDTO", "PT_OPSREGION", "Region Lead", "SERVICEDT"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Reordered Columns5", "ITEMGROUP", "ITEMGROUP - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"ITEMGROUP - Copy", "Product"}}),
    #"Added Custom3" = Table.AddColumn(#"Renamed Columns", "PT State", each ""),
    #"Reordered Columns6" = Table.ReorderColumns(#"Added Custom3",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "SOSTATUS", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_NEXTBILLDATE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "Workflow Flag", "WIPASSIGNEDTO", "PT_OPSREGION", "Region Lead", "Priority", "SERVICEDT", "Product", "PT State", "GoScripts", "Parachute", "SLA", "WIPSTATENAME"}),
    #"Added Custom4" = Table.AddColumn(#"Reordered Columns6", "TZ", each ""),
    #"Reordered Columns7" = Table.ReorderColumns(#"Added Custom4",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "Workflow Flag", "WIPASSIGNEDTO", "PT_OPSREGION", "Region Lead", "Priority", "SERVICEDT", "Product", "PT State", "GoScripts", "Parachute", "SLA", "WIPSTATENAME", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE"}),
    #"Added Custom5" = Table.AddColumn(#"Reordered Columns7", "DNC/EMR Access", each ""),
    #"Reordered Columns8" = Table.ReorderColumns(#"Added Custom5",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "WIPASSIGNEDTO", "PT_OPSREGION", "Region Lead", "Priority", "SERVICEDT", "Product", "PT State", "SLA", "WIPSTATENAME", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE"}),
    #"Added Custom6" = Table.AddColumn(#"Reordered Columns8", "Action", each ""),
    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "Notes", each ""),
    #"Reordered Columns9" = Table.ReorderColumns(#"Added Custom7",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "SODTLSTATUS", "U_SODTLKEY", "Wip Aging Bucket", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "WIPASSIGNEDTO", "Action", "Notes", "SOSTATUS", "Priority", "PT_OPSREGION", "Region Lead", "SERVICEDT", "Product", "PT State", "SLA", "WIPSTATENAME", "TZ", "DAYSFROM_NEXTBILLDATE"}),
    #"Added Custom8" = Table.AddColumn(#"Reordered Columns9", "Zero Balance", each ""),
    #"Reordered Columns10" = Table.ReorderColumns(#"Added Custom8",{"SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "Auth Leader", "REGIONALEXCLUSIONS", "MANUALHOLDREASON", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLPD", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD", "STOPPEDBILLING", "PARDATE_ACTIONTAKEN", "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "STOPREASON", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "STOP_AGING", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DATEOFDISCHARGE", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "U_SODTLKEY", "Wip Aging Bucket", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "WIPASSIGNEDTO", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "Product", "WIPSTATENAME"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns10",{"Product", "SNAPSHOT_DATE", "NICKNAME", "PATIENTID", "PT_BRANCHNAME", "SO_BRANCHNAME", "Auth Leader", "REGIONALEXCLUSIONS", "NEXTBILLDATE", "NEXTBILLDATE_FLAG", "NEXTBILLDT_AGING", "SO_CLASSIFICATION", "PROCCODE", "BILLQTY", "CHARGEAMT", "ALLOWAMT", "EXTALLOWAMT", "DAYSINWIP", "INVOICES_ON_HOLD", "INVOICEONHOLD",  "U_PARKEY", "PARNUMBER", "PAR_DESCRIPTION", "INITIAL_DATE", "EXP_DATE", "PAR_LOGDT", "PAR_LOGGED_BY", "ORDERSTOP_CHANGEDT", "SOSTOPDATE", "HOLD_STOP_GROUP", "STOP_GROUPING", "ACCOUNTNBR", "DAYSFROM_SERVICEDATE", "SOACTUALDELIVERYDATE", "SOCONFIRMDATE", "SOCREATEDATE", "SOCREATEDBY", "DONOTCALL_FLAG", "DONOTFAX_FLAG", "GOSCRIPTSENROLLED_FLAG", "INTERNALCONTACTNAME", "ORDERINGDOCTOR", "DOD_FLAG", "PUEXSTATNAME", "PUEXREASONNAME", "PUEXTYPENAME", "FINALBILLDT", "SODTLKEY", "U_SODTLKEY", "Wip Aging Bucket"}),
    #"Reordered Columns16" = Table.ReorderColumns(#"Removed Columns",{"MANUALHOLDREASON", "STOPPEDBILLING", "STOP_AGING", "SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "WIPASSIGNEDTO", "No Ratro Payor", "Exp Date Grouping", "Column1", "Column3", "Column4", "Column5", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "StLukes Vents", "WIPDate_ActiveDate", "FutureDated", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOPREASON"}),
    #"Reordered Columns11" = Table.ReorderColumns(#"Reordered Columns16",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "WIPASSIGNEDTO", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOP_AGING"}),
    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns11", {"SOKEY"}),
    #"Reordered Columns12" = Table.ReorderColumns(#"Removed Duplicates",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Retro Payer", "No Ratro Payor", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "WIPASSIGNEDTO", "Action", "Notes", "Exp Date Grouping", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOP_AGING", "STOPPEDBILLING"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns12",{"No Retro Payer", "Exp Date Grouping"}),
    #"Reordered Columns13" = Table.ReorderColumns(#"Removed Columns1",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Ratro Payor", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "WIPASSIGNEDTO", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOPPEDBILLING", "STOP_AGING"}),
    #"Added Custom9" = Table.AddColumn(#"Reordered Columns13", "Agent Assignment", each ""),
    #"Reordered Columns14" = Table.ReorderColumns(#"Added Custom9",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Ratro Payor", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "Agent Assignment", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOPPEDBILLING", "STOP_AGING", "WIPASSIGNEDTO"}),
    #"Filtered Rows1" = Table.SelectRows(#"Reordered Columns14", each ([StLukes Vents] = "")),
    #"Removed Columns2" = Table.RemoveColumns(#"Filtered Rows1",{"StLukes Vents", "Column1", "Column3", "Column4", "Column5"}),
    #"Reordered Columns15" = Table.ReorderColumns(#"Removed Columns2",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Ratro Payor", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPNEEDDT", "WIPDate_ActiveDate", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "Agent Assignment", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOPPEDBILLING", "STOP_AGING", "WIPASSIGNEDTO", "MANUALHOLDREASON"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns15",{"WIPNEEDDT", "FutureDated"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Removed Columns3",{{"WIPDate_ActiveDate", type date}}),
    #"Reordered Columns17" = Table.ReorderColumns(#"Changed Type4",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Ratro Payor", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPDate_ActiveDate", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "Agent Assignment", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOPPEDBILLING", "STOP_AGING", "WIPASSIGNEDTO", "STOPREASON", "MANUALHOLDREASON", "CALLATTEMPT", "NBD Grouping", "Fax Upload Date", "PARDATE_ACTIONTAKEN"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Reordered Columns17",{"Column6", "Insurance Sec Payor"}),
    #"Reordered Columns18" = Table.ReorderColumns(#"Removed Columns4",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Ratro Payor", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPDate_ActiveDate", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "Agent Assignment", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOPPEDBILLING", "STOP_AGING", "WIPASSIGNEDTO", "STOPREASON", "MANUALHOLDREASON", "CALLATTEMPT", "NBD Grouping", "Fax Upload Date", "PARDATE_ACTIONTAKEN", "DATEOFDISCHARGE"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Reordered Columns18",{"Column2", "Column22", "Column23"}),
    #"Reordered Columns19" = Table.ReorderColumns(#"Removed Columns5",{"SOKEY", "PAYORNAME", "POLICYNBR", "No Ratro Payor", "ITEMGROUP", "PAR_WORKFLOW", "File", "NPI", "WIPDate_ActiveDate", "DNC/EMR Access", "GoScripts", "Parachute", "Workflow Flag", "Agent Assignment", "Action", "Notes", "SODTLSTATUS", "Priority", "Zero Balance", "PT_OPSREGION", "Region Lead", "NC Medicaid", "SLA", "SERVICEDT", "PT State", "TZ", "SOSTATUS", "DAYSFROM_NEXTBILLDATE", "STOPPEDBILLING", "STOP_AGING", "WIPASSIGNEDTO", "STOPREASON", "MANUALHOLDREASON", "CALLATTEMPT", "NBD Grouping", "Fax Upload Date", "PARDATE_ACTIONTAKEN", "DATEOFDISCHARGE", "NEXTBILLPD", "WIPSTATENAME"})
in
    #"Reordered Columns19"