let
    Source = Excel.CurrentWorkbook(){[Name="Table3"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"OrderKey", type text}, {"OIP Teams Reports", type any}, {"Team Report", type text}, {"Created Date", type datetime}, {"Inbound Call", type text}, {"CallID", Int64.Type}, {"Site1", type text}, {"OrderID", Int64.Type}, {"Disposition/Conversions", type text}, {"Points", Int64.Type}, {"Agent Email", type text}, {"PatientID", type text}, {"InsCompName", type text}, {"End-State", type text}, {"InsuranceContactType", type text}, {"QMESPatientCall", type any}, {"VerifiedInsurance", type any}, {"Interaction ID", type any}, {"StateAddress", type text}, {"EscalationReason", type text}, {"Void", type text}, {"EscalatedAttempts", Int64.Type}, {"EscalationNote", type text}, {"Team Name", type text}, {"Commendation", type text}, {"QAAuditDate", type any}, {"QAAuditType", type any}, {"QAError", type any}, {"QASubError", type any}, {"QAError2", type any}, {"QASubError2", type any}, {"QAError3", type any}, {"QASubError3", type any}, {"QAComments", type any}, {"QAScore", type any}, {"QARCA", type any}, {"QACoachDate", type any}, {"Call ID", Int64.Type}, {"StateAddress2", type text}, {"Agent Email3", type text}, {"Number Of Attempts", Int64.Type}}),
    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"OrderKey", Order.Ascending}}),
    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"OrderKey"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each ([Team Report] <> "-")),
    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"Created Date", type date}}),
    #"Inserted First Characters" = Table.AddColumn(#"Changed Type1", "First Characters", each Text.Start([PatientID], 3), type text),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted First Characters",{"Created Date", "OrderKey", "OIP Teams Reports", "Team Report", "First Characters", "Inbound Call", "CallID", "Site1", "OrderID", "Disposition/Conversions", "Points", "Agent Email", "PatientID", "InsCompName", "End-State", "InsuranceContactType", "QMESPatientCall", "VerifiedInsurance", "Interaction ID", "StateAddress", "EscalationReason", "Void", "EscalatedAttempts", "EscalationNote", "Team Name", "Commendation", "QAAuditDate", "QAAuditType", "QAError", "QASubError", "QAError2", "QASubError2", "QAError3", "QASubError3", "QAComments", "QAScore", "QARCA", "QACoachDate", "Call ID", "StateAddress2", "Agent Email3", "Number Of Attempts"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"OIP Teams Reports", "Inbound Call", "Points", "Agent Email", "InsuranceContactType", "QMESPatientCall", "VerifiedInsurance", "Interaction ID", "StateAddress", "EscalationReason", "Void", "EscalatedAttempts", "EscalationNote", "Team Name", "Commendation", "QAAuditDate", "QAAuditType", "QAError", "QASubError", "QAError2", "QASubError2", "QAError3", "QASubError3", "QAComments", "QAScore", "QARCA", "QACoachDate", "Call ID", "StateAddress2", "Agent Email3", "Number Of Attempts"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns",{"Created Date", "OrderKey", "Team Report", "First Characters", "OrderID", "CallID", "Site1", "Disposition/Conversions", "PatientID", "InsCompName", "End-State"})
in
    #"Reordered Columns1"