STL Held

let
    Source = Excel.CurrentWorkbook(){[Name="Table4"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Invoice Number", Int64.Type}, {"Invoice Sales Order Number", Int64.Type}, {"Invoice Date Created", type datetime}, {"Invoice Date of Service", type datetime}, {"Invoice Branch", type text}, {"Invoice SO Manual Hold Reason", type text}, {"Invoice Aging Bucket - DOS", Int64.Type}, {"Invoice Aging Bucket - Create Date", Int64.Type}, {"Invoice SO Created By", type text}, {"Invoice SO Confirmed By", type text}, {"Patient ID", Int64.Type}, {"Patient DOB", type datetime}, {"Patient Branch", type text}, {"Patient Full Name", type text}, {"Policy Payor Name", type text}, {"Policy #", type any}, {"Policy Payor Level", type text}, {"Invoice Detail DOS From", type datetime}, {"Invoice Detail Billing Period", Int64.Type}, {"Invoice Detail Charge", type number}, {"Invoice Detail Allow", type number}, {"Invoice Detail Balance", type number}, {"Invoice Detail Qty", Int64.Type}, {"Invoice Detail Proc Code", type text}, {"Invoice Detail Modifier 1", type text}, {"Invoice Detail Item Group", type text}, {"Invoice Detail Original DOS", type datetime}, {"Invoice Detail Price Type", type text}, {"Ordering Doctor NPI", Int64.Type}, {"Ordering Doctor Full Name", type text}, {"Sales Order Hold CMN Not Logged", type logical}, {"Sales Order Hold CMN Expired", type logical}, {"Sales Order Hold PAR Not Logged", type logical}, {"Sales Order Hold PAR Expired", type logical}, {"Sales Order Hold Manual Hold", type logical}, {"Sales Order Stop Pending Pickup", type logical}, {"Sales Order Stop Multiple Pricing Options", type logical}, {"Sales Order Stop Policy Expired", type logical}, {"Sales Order Stop No Pricing Found", type logical}, {"Sales Order Stop Policy Changed", type logical}, {"Sales Order Stop Manual Stop Date", type logical}, {"Sales Order Stop Automatic Eligibility Check", type logical}, {"Sales Order Stop Ineligible Policy", type logical}, {"Sales Order Par Date Action Taken", type datetime}, {"Sales Order Custom Fields Field7", type text},  {"Sales Order Custom Fields Field9", type text},  {"Sales Order Custom Fields Field13", type text},{"Sales Order Custom Stop Reason", type text},{"Sales Order Par Workflow", type text}, {"Work In Progress WIP State", type text}, {"Work In Progress Assigned To", type text}, {"Work In Progress Date Needed", type datetime}, {"Work In Progress WIP Days In State", Int64.Type}, {"Inv Dtl Key", Int64.Type}, {"Region", type text}, {"Zero Balance", type text}, {"NBBD", type text}, {"NBD days", Int64.Type}, {"Regional Exclusions", type text}, {"DNC", type any}, {"DNC/EMR", type any}, {"Go Scripts", type any}, {"No Retro Payer Name", type any}, {"DOS Aging", type text}, {"DOS Days", Int64.Type}, {"Branch Group State", type text}, {"GoScripts Actual", type text}, {"Parachute Acutal", type text}, {"EMR", type text}, {"Region Lead", type text}, {"NC Medicaid", type any}, {"SLA Status", type text}, {"Status", type text}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Policy #", type text}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type1", {"Invoice Sales Order Number"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Invoice Date Created", type date}, {"Invoice Date of Service", type date}, {"Patient DOB", type date}, {"Invoice Detail DOS From", type date}, {"Invoice Detail Original DOS", type date}, {"Sales Order Par Date Action Taken", type date}, {"Work In Progress Date Needed", type date}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type2",{"Region", "Region Lead", "NC Medicaid", "EMR", "SLA Status", "Invoice Date of Service", "Invoice Number", "Invoice Sales Order Number", "Invoice Date Created", "Invoice Branch", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Patient ID", "Patient DOB", "Patient Branch", "Patient Full Name", "Policy Payor Name", "Policy #", "Policy Payor Level", "Invoice Detail DOS From", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Qty", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Invoice Detail Item Group", "Invoice Detail Original DOS", "Invoice Detail Price Type", "Ordering Doctor NPI", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order Par Date Action Taken", "Sales Order Custom Fields Field7",  "Sales Order Custom Fields Field9",  "Sales Order Custom Fields Field13",  "Sales Order Custom Stop Reason",  "Sales Order Par Workflow", "Work In Progress WIP State", "Work In Progress Assigned To", "Work In Progress Date Needed", "Work In Progress WIP Days In State", "Inv Dtl Key", "Zero Balance", "NBBD", "NBD days", "Regional Exclusions", "DNC", "DNC/EMR", "Go Scripts", "No Retro Payer Name", "DOS Aging", "DOS Days", "Branch Group State", "GoScripts Actual", "Parachute Acutal", "Status"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Reordered Columns",{"Status", "Priority", "Region", "Region Lead", "NC Medicaid", "EMR", "SLA Status", "Invoice Date of Service", "Invoice Number", "Invoice Sales Order Number", "Invoice Date Created", "Invoice Branch", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Patient ID", "Patient DOB", "Patient Branch", "Patient Full Name", "Policy Payor Name", "Policy #", "Policy Payor Level", "Invoice Detail DOS From", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Qty", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Invoice Detail Item Group", "Invoice Detail Original DOS", "Invoice Detail Price Type", "Ordering Doctor NPI", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order Par Date Action Taken", "Sales Order Custom Fields Field7", "Sales Order Custom Fields Field9",  "Sales Order Custom Fields Field13",  "Sales Order Custom Stop Reason", "Sales Order Par Workflow", "Work In Progress WIP State", "Work In Progress Assigned To", "Work In Progress Date Needed", "Work In Progress WIP Days In State", "Inv Dtl Key", "Zero Balance", "NBBD", "NBD days", "Regional Exclusions", "DNC", "DNC/EMR", "Go Scripts", "No Retro Payer Name", "DOS Aging", "DOS Days", "Branch Group State", "GoScripts Actual", "Parachute Acutal"}),
    #"Added Custom1" = Table.AddColumn(#"Reordered Columns1", "Notes", each ""),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Action", each ""),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Agent Assignment", each ""),
    #"Reordered Columns2" = Table.ReorderColumns(#"Added Custom3",{"Ordering Doctor NPI", "Work In Progress Date Needed", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Region", "Region Lead", "NC Medicaid", "EMR", "SLA Status", "Invoice Date of Service", "Invoice Number", "Invoice Sales Order Number", "Invoice Date Created", "Invoice Branch", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Patient ID", "Patient DOB", "Patient Branch", "Patient Full Name", "Policy Payor Name", "Policy #", "Policy Payor Level", "Invoice Detail DOS From", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Qty", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Invoice Detail Item Group", "Invoice Detail Original DOS", "Invoice Detail Price Type", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order Par Date Action Taken", "Sales Order Custom Fields Field7",  "Sales Order Custom Fields Field9", "Sales Order Custom Fields Field13",  "Sales Order Custom Stop Reason",  "Sales Order Par Workflow", "Work In Progress WIP State", "Work In Progress Assigned To", "Work In Progress WIP Days In State", "Inv Dtl Key", "Zero Balance", "NBBD", "NBD days", "Regional Exclusions", "DNC", "Go Scripts", "No Retro Payer Name", "DOS Aging", "DOS Days", "Branch Group State"}),
    #"Added Custom5" = Table.AddColumn(#"Reordered Columns2", "File", each "Manual Held"),
    #"Reordered Columns3" = Table.ReorderColumns(#"Added Custom5",{"Invoice Sales Order Number", "Patient ID", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Region", "Region Lead", "NC Medicaid", "EMR", "SLA Status", "Invoice Date of Service", "Invoice Number", "Invoice Date Created", "Invoice Branch", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Patient DOB", "Patient Branch", "Patient Full Name", "Policy Payor Level", "Invoice Detail DOS From", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Qty", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Invoice Detail Original DOS", "Invoice Detail Price Type", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order Par Date Action Taken", "Sales Order Custom Fields Field7", "Sales Order Custom Fields Field9",  "Sales Order Custom Fields Field13",  "Sales Order Custom Stop Reason",  "Work In Progress WIP State", "Work In Progress Assigned To", "Work In Progress WIP Days In State", "Inv Dtl Key", "Zero Balance", "NBBD", "NBD days", "Regional Exclusions", "DNC", "Go Scripts", "DOS Aging", "DOS Days", "Branch Group State"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns3",{"Invoice Number", "Invoice Date Created", "Invoice Branch", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Patient DOB", "Patient Branch", "Patient Full Name", "Policy Payor Level", "Invoice Detail DOS From", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Qty", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Invoice Detail Original DOS", "Invoice Detail Price Type", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order Custom Fields Field7",  "Sales Order Custom Fields Field9","Sales Order Custom Fields Field13", "Work In Progress WIP Days In State", "Inv Dtl Key", "NBBD", "NBD days","Regional Exclusions", "DNC", "Go Scripts", "DOS Aging", "DOS Days", "Branch Group State"}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Removed Columns",{"Invoice Sales Order Number", "Patient ID", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "DNC/EMR", "GoScripts Actual", "Parachute Acutal",  "Agent Assignment", "Action", "Notes", "Status", "Priority", "Region", "Region Lead", "NC Medicaid", "EMR", "SLA Status", "Invoice Date of Service", "Patient State"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns4",{"Patient ID", "Patient Phone", "Patient Postal Code", "Patient DOD", "Policy Payor ID", "EMR"}),
    #"Reordered Columns5" = Table.ReorderColumns(#"Removed Columns1",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region", "Region Lead", "NC Medicaid", "SLA Status", "Invoice Date of Service", "Patient State", "Team Leader", "Wip Aging Bucket", "WF Flag"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns5",{"Team Leader", "Wip Aging Bucket"}),
    #"Reordered Columns6" = Table.ReorderColumns(#"Removed Columns2",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "WF Flag", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region", "Region Lead", "NC Medicaid", "SLA Status", "Invoice Date of Service", "Patient State"}),
    #"Sorted Rows" = Table.Sort(#"Reordered Columns6",{{"Work In Progress Date Needed", Order.Ascending}}),
    #"Added Custom4" = Table.AddColumn(#"Sorted Rows", "SO Status", each ""),
    #"Added Custom6" = Table.AddColumn(#"Added Custom4", "Days from NBD", each ""),
    #"Added Custom7" = Table.AddColumn(#"Added Custom6", "STOPPEDBILLING", each ""),
    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Stop Aging", each ""),
    #"Reordered Columns7" = Table.ReorderColumns(#"Added Custom8",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "WF Flag", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region", "Region Lead", "NC Medicaid", "SLA Status", "Invoice Date of Service", "Patient State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns7",{"Column1", "Vent Exclude", "Column2", "Invoice SO Classification"}),
    #"Reordered Columns8" = Table.ReorderColumns(#"Removed Columns3",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "WIPDate_ActionDate", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "WF Flag", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region", "Region Lead", "NC Medicaid", "SLA Status", "Sales Order Par Date Action Taken", "Invoice Date of Service", "Patient State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns8",{{"WIPDate_ActionDate", type date}}),
    #"Removed Columns4" = Table.RemoveColumns(#"Changed Type3",{"Work In Progress Date Needed"}),
    #"Reordered Columns9" = Table.ReorderColumns(#"Removed Columns4",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "WIPDate_ActionDate", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "WF Flag", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region", "Region Lead", "NC Medicaid", "SLA Status", "Invoice Date of Service", "Patient State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To", "Sales Order Par Date Action Taken", "Sales Order Custom Stop Reason", "Invoice SO Manual Hold Reason", "CALLATTEMPT", "NBD Grouping", "Column3"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns9",{{"Column3", "Fax Upload Date"}}),
    #"Reordered Columns10" = Table.ReorderColumns(#"Renamed Columns",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "WIPDate_ActionDate", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "WF Flag", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region", "Region Lead", "NC Medicaid", "SLA Status", "Invoice Date of Service", "Patient State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To", "Sales Order Custom Stop Reason", "Invoice SO Manual Hold Reason", "CALLATTEMPT", "NBD Grouping", "Fax Upload Date", "Sales Order Par Date Action Taken", "Work In Progress WIP State"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Reordered Columns10",{"Insurance Sec Payor"}),
    #"ADDED DateOfDischarge col" = Table.AddColumn(#"Removed Columns5", "DateOfDischarge", each null),
    #"ADDED NEXTBILLPD col" = Table.AddColumn(#"ADDED DateOfDischarge col", "NEXTBILLPD", each null),
    #"Reordered Columns11" = Table.ReorderColumns(#"ADDED NEXTBILLPD col",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Payer Name", "Invoice Detail Item Group", "Sales Order Par Workflow", "File", "Ordering Doctor NPI", "WIPDate_ActionDate", "DNC/EMR", "GoScripts Actual", "Parachute Acutal", "WF Flag", "Agent Assignment", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region", "Region Lead", "NC Medicaid", "SLA Status", "Invoice Date of Service", "Patient State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To", "Sales Order Custom Stop Reason", "Invoice SO Manual Hold Reason", "CALLATTEMPT", "NBD Grouping", "Fax Upload Date", "Sales Order Par Date Action Taken", "DateOfDischarge", "NEXTBILLPD", "Work In Progress WIP State"})
in
    #"Reordered Columns11"