HELD Prod Camp Files

let
    Source = Folder.Files("C:\Users\Administrator\Downloads\HELD PROD CAMP FILES"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (2)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"CallID", Int64.Type}, {"Campaign", type text}, {"Direction", type text}, {"From", Int64.Type}, {"To", Int64.Type}, {"AgentID", Int64.Type}, {"AgentEmail", type text}, {"StartTime", type datetime}, {"Duration", Int64.Type}, {"Result", type text}, {"LeadID", Int64.Type}, {"ExternalLeadID", type text}, {"PubID", type any}, {"SubID", type any}, {"TalkTime", Int64.Type}, {"WrapUpDuration", Int64.Type}, {"CompletedDate", type datetime}}),
    #"1. REMOVED Source.Name col" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
    #"2. FILTERED SnapHeld only" = Table.SelectRows(#"1. REMOVED Source.Name col", each ([Campaign] <> "" and [Campaign] <> " PR 00987-2208 - outside US""")),
    #"3. FILTERED OUT Null AgentEmail" = Table.SelectRows(#"2. FILTERED SnapHeld only", each [AgentID] <> null and [AgentID] <> "")
in
    #"3. FILTERED OUT Null AgentEmail"

--------------------------------------------------------------------------------------------------------------------------------------

Raw Data

let
    Source = Excel.Workbook(File.Contents("G:\Shared drives\Ramel\Tusoy_Reports\Raw Data-Combined.xlsx"), null, true),
    Data_Sheet = Source{[Item="Data",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"unqid", type text}, {"LastDoctorCallCount", Int64.Type}, {"LastDoctorDisposition", type text}, {"LastDoctorAttemptDate", type date}, {"LastPatientCallCount", Int64.Type}, {"LastPatientDisposition", type text}, {"LastPatientAttemptDate", type date}, {"LastMedicalNoteOnlyCallCount", Int64.Type}, {"LastMedicalNoteOnlyDisposition", type any}, {"LastMedicalNoteOnlyAttemptDate", type any}, {"LastMedicalNotePatientCallCount", Int64.Type}, {"LastMedicalNotePatientCallDisposition", type any}, {"LastMedicalNotePatientCallAttemptDate", type any}, {"LastReworkCallCount", Int64.Type}, {"LastReworkDisposition", type any}, {"LastReworkAttemptDate", type any}, {"DNC", type text}, {"DNF", type text}, {"UseEmail", type text}, {"POC", type text}, {"UseClientPhoneFaxOnly", type text}, {"CallFirst", type text}, {"UseEDocumentService", type text}, {"EDocumentServiceName", type text}, {"Email", type any}, {"PhoneNumbers", type number}, {"FaxNumbers", type number}, {"SalesRep", type text}, {"LastFaxDate", type any}, {"LastFaxResult", type any}, {"LastFaxCampaign", type any}, {"LastTouchedDate", type date}, {"DaysSinceWorked", Int64.Type}, {"Recd_Date", type date}, {"Client", type text}, {"SubClient", type text}, {"FirstName", type text}, {"LastName", type text}, {"ProductCode", type text}, {"AilmentType", type text}, {"Address", type text}, {"Address2", type text}, {"City", type text}, {"State", type text}, {"Zip", type text}, {"HomePhone", Int64.Type}, {"DateOfBirth", type date}, {"PatientFollowUpDate", type date}, {"DoctorNpi", Int64.Type}, {"DoctorFirstName", type text}, {"DoctorLastName", type text}, {"DoctorAddress", type text}, {"DoctorAddress2", type text}, {"DoctorCity", type text}, {"DoctorState", type text}, {"DoctorZip", Int64.Type}, {"DoctorPhone", Int64.Type}, {"DoctorFax", Int64.Type}, {"DoctorUpdated", type text}, {"Status", type text}, {"SubStatus", type text}, {"StatusDate", type date}, {"pmcnumber", type any}, {"dnf", type text}, {"Chart_Id", Int64.Type}, {"Age", type text}, {"MI", type any}, {"File_Name", type text}, {"Entry_Date", type date}, {"Upload_date", type date}, {"RxDate", type any}, {"MedicalRecordsDate", type any}, {"VerificationDate", type any}, {"Medi_Adv_Carrier", type text}, {"Medi_Adv_Mem_ID", type any}, {"Medi_Adv_Carrier_Phone", type any}, {"Medi_Adv_Address", type any}, {"Medi_Adv_Address2", type any}, {"Medi_Adv_City", type any}, {"Medi_Adv_State", type any}, {"Medi_Adv_Zip", type any}, {"In_Net", type any}, {"Deductible", type any}, {"co_pay_per", type any}, {"co_pay_total", type any}, {"OOP_Cost", type any}, {"Medi_Sup_Ins_Name", type any}, {"Medi_Sup_Ins_Mem_ID", type any}, {"Medi_Sup_Ins_Phone", type any}, {"Medi_Sup_Ins_Address", type any}, {"Medi_Sup_Ins_Address2", type any}, {"Medi_Sup_Ins_City", type any}, {"Medi_Sup_Ins_State", type any}, {"Medi_Sup_Ins_Zip", type any}, {"ss_status", type text}, {"ins_status", type text}, {"pecos_status", type text}, {"Custom1", Int64.Type}, {"Custom2", Int64.Type}, {"Custom3", Int64.Type}, {"Custom4", type text}, {"Custom5", type text}, {"Custom6", type text}, {"Custom7", type text}, {"Custom8", type text}, {"Custom9", type text}, {"Custom10", type date}, {"Custom11", type number}, {"Custom12", type text}, {"Custom13", type text}, {"Custom14", type any}, {"Custom15", type any}, {"SourceCode", type text}, {"PCN", type any}, {"BIN", Int64.Type}, {"PrescriptionGroup", type any}, {"ClientName", type text}, {"FollowUpDate", type any}, {"SameSimilarDate", type any}, {"SameSimilarCompany", type any}, {"SameSimilarHCPCS", type any}, {"RxChaseFaxStatus", type text}, {"RxChaseFaxSuccess", Int64.Type}, {"RxChaseFaxFail", Int64.Type}, {"RxChaseFaxLastAttempt", type any}, {"Medications", type any}, {"BrandName", type text}, {"BtInstance", type text}, {"AgingReceivedDays", Int64.Type}, {"AgingEntryDays", Int64.Type}, {"Days Grouping", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"dnf", "dnf.1"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"unqid", "SubStatus", "Days Grouping"})
in
    #"Removed Other Columns"