Active Orders M Code

let
    Source = Folder.Files("C:\Users\AlodiaBendicio\Downloads\Active Orders"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"Document Count", Int64.Type}, {"Insurance Count", Int64.Type}, {"Doctor Count", Int64.Type}, {"Order ID", Int64.Type}, {"Brightree Order ID", type any}, {"Athena Order ID", type any}, {"Bonafide Order ID", type any}, {"Universal Order ID", type any}, {"TIMS Order ID", type any}, {"CPRPlus Order ID", type any}, {"Niko Order ID", type any}, {"Patient ID", Int64.Type}, {"Brightree Patient ID", Int64.Type}, {"Athena Patient ID", type any}, {"Bonafide Patient ID", type any}, {"Universal Patient ID", type any}, {"TIMS Patient ID", type any}, {"CPRPlus Patient ID", type any}, {"Niko Patient ID", type any}, {"Patient Name", type text}, {"Patient Email", type text}, {"Patient DOB", type date}, {"Primary Ins Plan", type text}, {"Primary Ins Is Medicare", type logical}, {"Owned By", type text}, {"Branch", type text}, {"Branch Region", type any}, {"From Company", type text}, {"Latest Company", type text}, {"Booked Date", type date}, {"Booked By", type text}, {"Item List", type text}, {"Pre-Ship Issues", type text}, {"Order Notes", type text}, {"Split Shipping", type any}, {"Order Type", type text}, {"Reship Reason", type any}, {"Medicare", type logical}, {"Primary Doctor", type text}, {"Secondary Doctor", type text}, {"Shipping Address", type text}, {"Shipping Vendor", type text}, {"Shipping Method", type text}, {"Order State", type text}, {"Void Reason", type any}, {"Sent to Shipper Date", type date}, {"Shipped Date", type any}, {"Date of Service", type any}, {"Sent to Therapist", type logical}, {"CPAP Mask Manuf", type text}, {"In State Since", type text}, {"Worked By", type text}, {"Ins Actions", Int64.Type}, {"Ins Worked First Date", type date}, {"Ins Worked Last Date", type date}, {"Doc Actions", Int64.Type}, {"Doc Worked First Date", type date}, {"Doc Worked Last Date", type date}, {"Rx Needed", type logical}}),
    #"1. Deleted first column (source name)" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
    #"2. Reverse Filtered Column Y (Primary Ins Plan)" = Table.SelectRows(#"1. Deleted first column (source name)", each not Text.Contains([Primary Ins Plan], "NEW YORK HOTEL & TRADE  1") and not Text.Contains([Primary Ins Plan], "EMPLOYEE BENEFIT MGMT SERVICES INC") and not Text.Contains([Primary Ins Plan], "LI World Trade Claim Administration") and not Text.Contains([Primary Ins Plan], "UMR - WTC Program") and not Text.Contains([Primary Ins Plan], "UMR - WTC Program (Medstar Only)") and not Text.Contains([Primary Ins Plan], "World Trade Center National Responder Health Progr") and not Text.Contains([Primary Ins Plan], "WTC FDNY - _ - _ - _ - _") and not Text.Contains([Primary Ins Plan], "WTC FDNY") and not Text.Contains([Primary Ins Plan], "WTC Health Program")),
    #"3. Reverse Filtered Column AE (Latest Company)" = Table.SelectRows(#"2. Reverse Filtered Column Y (Primary Ins Plan)", each not Text.Contains([Latest Company], "Synapse")),
    #"4. Reverse Filtered Column AO (Primary Doctor)" = Table.SelectRows(#"3. Reverse Filtered Column AE (Latest Company)", each not Text.Contains([Primary Doctor], "Thanuja Hamilton")),
    #"5. Changed Northshore -> HME" = Table.ReplaceValue(#"4. Reverse Filtered Column AO (Primary Doctor)","Northshore University Health System","Home Medical Express",Replacer.ReplaceText,{"Owned By"}),
    #"6. Changed [Latest Company] = [Owned By]" = Table.AddColumn(#"5. Changed Northshore -> HME", "Updated Owned By", each if [Latest Company] = "Family Medical Supply" then "Family Medical Supply" else [Owned By]),
    #"Reorder Updated [Owned By]" = Table.ReorderColumns(#"6. Changed [Latest Company] = [Owned By]",{"Document Count", "Insurance Count", "Doctor Count", "Order ID", "Brightree Order ID", "Athena Order ID", "Bonafide Order ID", "Universal Order ID", "TIMS Order ID", "CPRPlus Order ID", "Niko Order ID", "Patient ID", "Brightree Patient ID", "Athena Patient ID", "Bonafide Patient ID", "Universal Patient ID", "TIMS Patient ID", "CPRPlus Patient ID", "Niko Patient ID", "Patient Name", "Patient Email", "Patient DOB", "Primary Ins Plan", "Primary Ins Is Medicare", "Owned By", "Updated Owned By", "Branch", "Branch Region", "From Company", "Latest Company", "Booked Date", "Booked By", "Item List", "Pre-Ship Issues", "Order Notes", "Split Shipping", "Order Type", "Reship Reason", "Medicare", "Primary Doctor", "Secondary Doctor", "Shipping Address", "Shipping Vendor", "Shipping Method", "Order State", "Void Reason", "Sent to Shipper Date", "Shipped Date", "Date of Service", "Sent to Therapist", "CPAP Mask Manuf", "In State Since", "Worked By", "Ins Actions", "Ins Worked First Date", "Ins Worked Last Date", "Doc Actions", "Doc Worked First Date", "Doc Worked Last Date", "Rx Needed"}),
    #"Removed Orig [Owned By]" = Table.RemoveColumns(#"Reorder Updated [Owned By]",{"Owned By"}),
    #"Renamed Updated [Owned By]" = Table.RenameColumns(#"Removed Orig [Owned By]",{{"Updated Owned By", "Owned By"}}),
    #"7. Removed [Owned By] Buffalo CPAP" = Table.SelectRows(#"Renamed Updated [Owned By]", each [Owned By] <> "Buffalo CPAP")
in
    #"7. Removed [Owned By] Buffalo CPAP"