AERO Held

let
    Source = Excel.CurrentWorkbook(){[Name="Table3"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Invoice Number", Int64.Type}, {"Invoice Sales Order Number", Int64.Type}, {"Invoice Date Created", type datetime}, {"Invoice Date of Service", type datetime}, {"Invoice Branch", type text}, {"Invoice Branch Group", type text}, {"Invoice SO Classification", type text}, {"Invoice SO Manual Hold Reason", type any}, {"Invoice Aging Bucket - DOS", Int64.Type}, {"Invoice Aging Bucket - Create Date", Int64.Type}, {"Invoice SO Created By", type text}, {"Invoice SO Confirmed By", type text}, {"Invoice Balances Charge Total", type number}, {"Invoice Balances Allow Total", type number}, {"Invoice Balances Payments", Int64.Type}, {"Invoice Balances Balance", type number}, {"Patient State", type text}, {"Patient DOB", type datetime}, {"Patient DOD", type any}, {"Patient Branch", type text}, {"Patient Full Name", type text}, {"Policy Payor Name", type text}, {"Policy Payor ID", Int64.Type}, {"Policy #", type any}, {"Invoice Detail Item ID", type any}, {"Invoice Detail Item Name", type text}, {"Invoice Detail Billing Period", Int64.Type}, {"Invoice Detail Charge", type number}, {"Invoice Detail Allow", type number}, {"Invoice Detail Balance", type number}, {"Invoice Detail Proc Code", type text}, {"Invoice Detail Modifier 1", type text}, {"Invoice Detail Item Group", type text}, {"Marketing Rep Full Name", type text}, {"Referral Type", type text}, {"Referral Name", type text}, {"Referral NPI", Int64.Type}, {"Referring Provider Type", type text}, {"Referring Provider Name", type text}, {"Referring Provider NPI", type any}, {"Ordering Doctor NPI", Int64.Type}, {"Ordering Doctor Full Name", type text}, {"Sales Order Hold CMN Not Logged", type logical}, {"Sales Order Hold CMN Expired", type logical}, {"Sales Order Hold PAR Not Logged", type logical}, {"Sales Order Hold PAR Expired", type logical}, {"Sales Order Hold Manual Hold", type logical}, {"Sales Order Stop Pending Pickup", type logical}, {"Sales Order Stop Multiple Pricing Options", type logical}, {"Sales Order Stop Policy Expired", type logical}, {"Sales Order Stop No Pricing Found", type logical}, {"Sales Order Stop Policy Changed", type logical}, {"Sales Order Stop Manual Stop Date", type logical}, {"Sales Order Stop Automatic Eligibility Check", type logical}, {"Sales Order Stop Ineligible Policy", type logical}, {"Sales Order PAR Workflow", type text}, {"Sales Order Stopped Billing", type text}, {"Sales Order PAR Date Action Taken", type any}, {"Sales Order ARP", type any}, {"Work In Progress WIP State", type text}, {"Work In Progress Assigned To", type text}, {"Work In Progress Date Needed", type datetime}, {"Work In Progress WIP Days In State", Int64.Type}, {"Region", type text}, {"DNC/EMR", type any}, {"Item Grouping", type text}, {"Regional Exclusions", type text}, {"Auth Leader", type text}, {"No Retro Auth Payer Name", type any}, {"DOS Aging", type text}, {"DOS Days", Int64.Type}, {"Branch Group State", type text}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Invoice Sales Order Number"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Invoice Date of Service", type date}, {"Invoice Date Created", type date}, {"Patient DOB", type date}, {"Sales Order PAR Date Action Taken", type date}, {"Work In Progress Date Needed", type date}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type1",{"PAR WORKFLOW", "Work In Progress Assigned To", "Region", "Auth Leader", "Invoice Date of Service", "Invoice Number", "Invoice Sales Order Number", "Invoice Date Created", "Invoice Branch", "Invoice Branch Group", "Invoice SO Classification", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Invoice Balances Charge Total", "Invoice Balances Allow Total", "Invoice Balances Payments", "Invoice Balances Balance", "Patient State", "Patient DOB", "Patient DOD", "Patient Branch", "Patient Full Name", "Policy Payor Name", "Policy Payor ID", "Policy #", "Invoice Detail Item ID", "Invoice Detail Item Name", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Invoice Detail Item Group", "Marketing Rep Full Name", "Referral Type", "Referral Name", "Referral NPI", "Referring Provider Type", "Referring Provider Name", "Referring Provider NPI", "Ordering Doctor NPI", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order PAR Workflow", "Sales Order Stopped Billing", "Sales Order PAR Date Action Taken", "Sales Order ARP", "Work In Progress WIP State", "Work In Progress Date Needed", "Work In Progress WIP Days In State", "DNC/EMR", "Item Grouping", "Regional Exclusions", "No Retro Auth Payer Name", "DOS Aging", "DOS Days", "Branch Group State", "WIP Date Needed"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"PAR WORKFLOW", "PAR WORKFLOW Flag"}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns",{"Ordering Doctor NPI", "Work In Progress Date Needed", "PAR WORKFLOW Flag", "Work In Progress Assigned To", "Region", "Auth Leader", "Invoice Date of Service", "Invoice Number", "Invoice Sales Order Number", "Invoice Date Created", "Invoice Branch", "Invoice Branch Group", "Invoice SO Classification", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Invoice Balances Charge Total", "Invoice Balances Allow Total", "Invoice Balances Payments", "Invoice Balances Balance", "Patient State", "Patient DOB", "Patient DOD", "Patient Branch", "Patient Full Name", "Policy Payor Name", "Policy Payor ID", "Policy #", "Invoice Detail Item ID", "Invoice Detail Item Name", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Invoice Detail Item Group", "Marketing Rep Full Name", "Referral Type", "Referral Name", "Referral NPI", "Referring Provider Type", "Referring Provider Name", "Referring Provider NPI", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order PAR Workflow", "Sales Order Stopped Billing", "Sales Order PAR Date Action Taken", "Sales Order ARP", "Work In Progress WIP State", "Work In Progress WIP Days In State", "DNC/EMR", "Item Grouping", "Regional Exclusions", "No Retro Auth Payer Name", "DOS Aging", "DOS Days", "Branch Group State", "WIP Date Needed"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns1", "File", each "Manual Held"),
    #"Reordered Columns2" = Table.ReorderColumns(#"Added Custom",{"Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "PAR WORKFLOW Flag", "Work In Progress Assigned To", "Region", "Auth Leader", "Invoice Date of Service", "Invoice Number", "Invoice Sales Order Number", "Invoice Date Created", "Invoice Branch", "Invoice Branch Group", "Invoice SO Classification", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Invoice Balances Charge Total", "Invoice Balances Allow Total", "Invoice Balances Payments", "Invoice Balances Balance", "Patient State", "Patient DOB", "Patient DOD", "Patient Branch", "Patient Full Name", "Policy Payor Name", "Policy Payor ID", "Policy #", "Invoice Detail Item ID", "Invoice Detail Item Name", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Marketing Rep Full Name", "Referral Type", "Referral Name", "Referral NPI", "Referring Provider Type", "Referring Provider Name", "Referring Provider NPI", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order Stopped Billing", "Sales Order PAR Date Action Taken", "Sales Order ARP", "Work In Progress WIP State", "Work In Progress WIP Days In State", "DNC/EMR", "Item Grouping", "Regional Exclusions", "No Retro Auth Payer Name", "DOS Aging", "DOS Days", "Branch Group State", "WIP Date Needed"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Reordered Columns2", "Invoice Detail Item Group", "Invoice Detail Item Group - Copy"),
    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Invoice Detail Item Group - Copy", "Product"}}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Renamed Columns1",{"Invoice Sales Order Number", "Policy Payor ID", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "PAR WORKFLOW Flag", "Work In Progress Assigned To", "Region", "Auth Leader", "Invoice Date of Service", "Product", "Invoice Number", "Invoice Date Created", "Invoice Branch", "Invoice Branch Group", "Invoice SO Classification", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Invoice Balances Charge Total", "Invoice Balances Allow Total", "Invoice Balances Payments", "Invoice Balances Balance", "Patient State", "Patient DOB", "Patient DOD", "Patient Branch", "Patient Full Name", "Invoice Detail Item ID", "Invoice Detail Item Name", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Marketing Rep Full Name", "Referral Type", "Referral Name", "Referral NPI", "Referring Provider Type", "Referring Provider Name", "Referring Provider NPI", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order Stopped Billing", "Sales Order PAR Date Action Taken", "Sales Order ARP", "Work In Progress WIP State", "Work In Progress WIP Days In State", "DNC/EMR", "Item Grouping", "Regional Exclusions", "DOS Aging", "DOS Days", "Branch Group State", "WIP Date Needed"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns3",{"Invoice Number", "Invoice Date Created", "Invoice Branch", "Invoice Branch Group", "Invoice SO Classification", "Invoice SO Manual Hold Reason", "Invoice Aging Bucket - DOS", "Invoice Aging Bucket - Create Date", "Invoice SO Created By", "Invoice SO Confirmed By", "Invoice Balances Charge Total", "Invoice Balances Allow Total", "Invoice Balances Payments", "Invoice Balances Balance", "Patient DOB", "Patient DOD", "Patient Branch", "Patient Full Name", "Invoice Detail Item ID", "Invoice Detail Item Name", "Invoice Detail Billing Period", "Invoice Detail Charge", "Invoice Detail Allow", "Invoice Detail Balance", "Invoice Detail Proc Code", "Invoice Detail Modifier 1", "Marketing Rep Full Name", "Referral Type", "Referral Name", "Referral NPI", "Referring Provider Type", "Referring Provider Name", "Referring Provider NPI", "Ordering Doctor Full Name", "Sales Order Hold CMN Not Logged", "Sales Order Hold CMN Expired", "Sales Order Hold PAR Not Logged", "Sales Order Hold PAR Expired", "Sales Order Hold Manual Hold", "Sales Order Stop Pending Pickup", "Sales Order Stop Multiple Pricing Options", "Sales Order Stop Policy Expired", "Sales Order Stop No Pricing Found", "Sales Order Stop Policy Changed", "Sales Order Stop Manual Stop Date", "Sales Order Stop Automatic Eligibility Check", "Sales Order Stop Ineligible Policy", "Sales Order ARP",  "Work In Progress WIP Days In State", "DNC/EMR", "Item Grouping", "Regional Exclusions", "DOS Aging", "DOS Days", "Branch Group State", "WIP Date Needed", "Zero Balance"}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Removed Columns",{"Invoice Sales Order Number", "Policy Payor ID", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "PAR WORKFLOW Flag", "Work In Progress Assigned To", "Region", "Auth Leader", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns4",{"Policy Payor ID"}),
    #"Reordered Columns5" = Table.ReorderColumns(#"Removed Columns1",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "PAR WORKFLOW Flag", "Work In Progress Assigned To", "Region", "Auth Leader", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns5",{"Auth Leader", "Patient Postal Code", "Patient Phone", "Patient ID", "Invoice Detail Price Type", "Sales Order Custom Fields Field9", "Sales Order Custom Fields Field17", "EXTRA"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns2",{{"PAR WORKFLOW Flag", "PAR WORKFLOW"}}),
    #"Reordered Columns6" = Table.ReorderColumns(#"Renamed Columns2",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "PAR WORKFLOW", "Work In Progress Assigned To", "Region", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns6",{"PAR WORKFLOW"}),
    #"Reordered Columns7" = Table.ReorderColumns(#"Removed Columns3",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "Workflow Flag", "Work In Progress Assigned To", "Region", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ"}),
    #"Added Custom1" = Table.AddColumn(#"Reordered Columns7", "SO Status", each ""),
    #"Removed Columns4" = Table.RemoveColumns(#"Added Custom1",{ "Wip Aging Bucket"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns4",{{"Work In Progress Date Needed", Order.Ascending}}),
    #"Added Custom2" = Table.AddColumn(#"Sorted Rows", "Days from NBD", each ""),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "STOPPEDBILLING", each ""),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Stop Aging", each ""),
    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Assigned To", each ""),
    #"Reordered Columns8" = Table.ReorderColumns(#"Added Custom5",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "Work In Progress Date Needed", "Workflow Flag", "Assigned To", "Region", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Reordered Columns8",{"Priority"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns5",{{"WIPDate_ActionDate", type date}}),
    #"Reordered Columns9" = Table.ReorderColumns(#"Changed Type2",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "WIPDate_ActionDate", "Work In Progress Date Needed", "Workflow Flag", "Assigned To", "Region", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To"}),
    #"Removed Columns6" = Table.RemoveColumns(#"Reordered Columns9",{"Work In Progress Date Needed", "Column1"}),
    #"Reordered Columns10" = Table.ReorderColumns(#"Removed Columns6",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "WIPDate_ActionDate", "Workflow Flag", "Assigned To", "Region", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To", "Sales Order PAR Date Action Taken", "Vents", "Payer", "NBD Grouping"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns10",{{"Vents", "ManualHoldReason"}, {"Payer", "CallAttempts"}}),
    #"Reordered Columns11" = Table.ReorderColumns(#"Renamed Columns3",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "WIPDate_ActionDate", "Workflow Flag", "Assigned To", "Region", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To", "Sales Order Stopped Billing", "ManualHoldReason", "CallAttempts", "NBD Grouping", "Sales Order PAR Date Action Taken"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns11",{{"Sales Order PAR Date Action Taken", type date}}),
    #"Added Custom6" = Table.AddColumn(#"Changed Type3", "Fax Upload Date", each ""),
    #"Reordered Columns12" = Table.ReorderColumns(#"Added Custom6",{"Invoice Sales Order Number", "Policy Payor Name", "Policy #", "No Retro Auth Payer Name", "Invoice Detail Item Group", "Sales Order PAR Workflow", "File", "Ordering Doctor NPI", "WIPDate_ActionDate", "Workflow Flag", "Assigned To", "Region", "Region Lead", "Invoice Date of Service", "Product", "Patient State", "GoScripts", "Parachute", "SLA", "Work In Progress WIP State", "TZ", "SO Status", "Days from NBD", "STOPPEDBILLING", "Stop Aging", "Work In Progress Assigned To", "Sales Order Stopped Billing", "ManualHoldReason", "CallAttempts", "NBD Grouping", "Fax Upload Date", "Sales Order PAR Date Action Taken"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Reordered Columns12",{{"Fax Upload Date", type date}}),
    #"Removed Columns7" = Table.RemoveColumns(#"Changed Type4",{"Insurance Sec Payor", "FAX INTAKE NOTES", "FAX INTAKE NOTES2"})
in
    #"Removed Columns7"