STL FuturePars

let
    Source = Excel.CurrentWorkbook(){[Name="Table3"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Sales Order Number", Int64.Type}, {"Sales Order Created by", type text}, {"Sales Order Branch Office", type text}, {"Sales Order Status", type text}, {"Sales Order Manual Stop Reason", type text}, {"Sales Order Manual Hold Reason", type text}, {"Sales Order Custom Fields Field1", type text}, {"Sales Order Custom Fields Field7 (Stopped Billing Field)", type text}, {"Sales Order Custom Fields Field9", type date}, {"Sales Order Custom Fields Field17", type text}, {"Sales Order Custom Fields Field18", type date}, {"Sales Order Stop Type", type text}, {"Work In Progress WIP State", type text}, {"Work In Progress Assigned To", type text}, {"Work In Progress Date Needed", type datetime}, {"Work In Progress WIP Days In State", Int64.Type}, {"Delivery Actual date", type datetime}, {"Patient ID", Int64.Type}, {"Patient Email Address", type text}, {"Patient Address 1", type text}, {"Patient Address 2", type text}, {"Patient City", type text}, {"Patient State", type text}, {"Patient Postal Code", Int64.Type}, {"Patient Phone", Int64.Type}, {"Patient Mobile", Int64.Type}, {"Patient DOB", type date}, {"Patient DOD", type any}, {"Patient Branch", type text}, {"Patient Full Name", type text}, {"Ordering Doctor Doc NPI", Int64.Type}, {"Ordering Doctor Full Name", type text}, {"Ordering Doctor Group", type text}, {"Ordering Doctor Enrolled with Go Scripts", type text}, {"Ordering Doctor Preferred Method of Contact", type any}, {"Insurance Pri Payor", type text}, {"Insurance Pri Payor ID", Int64.Type}, {"Insurance Pri Policy #", type text}, {"Insurance Sec Payor", type text}, {"Sales Order Detail Next Period", Int64.Type}, {"Sales Order Detail Proc Code", type text}, {"Sales Order Detail Item Group", type text}, {"Sales Order Detail Next Date Of Service", type datetime}, {"Sales Order Detail Extended Allowance Amount", type number}, {"Sales Order Detail Diagnosis Codes Dx ICD-10 Code #01", type text}, {"CMN/PAR PAR", type text}, {"CMN/PAR PAR Descr", type text}, {"CMN/PAR PAR Init", type datetime}, {"CMN/PAR PAR Exp", type datetime}, {"CMN/PAR PAR Logged Date", type datetime}, {"CMN/PAR PAR Logged By", type text}, {"Days from Exp Date", Int64.Type}, {"Region Mapping.Region", type text}, {"Hold Exclusions.Hold Category", type text}, {"Stop Exclusions.Stop Category", type any}, {"Exp Date Grouping", type text}, {"Days from NBD", Int64.Type}, {"NBD Grouping ", type text}, {"Assigned?", type text}, {"Auth Covers?", type logical}, {"ItemMapping", type text}, {"Regional Exclusions1", type text}, {"DNC Connection.DNC/EMR Access?", type text}, {"NO RETRO PAYER", type text}, {"CCI Description,", type text}, {"USER1", type any}, {"USER2", Int64.Type}, {"WIP Date Needed", type text}, {"GoScripts", type text}, {"Parachute", type text}, {"SLA", type text}, {"TZ", type text}, {"Region Lead", type text}, {"Priority", type any}, {"File Arrangement", type any}, {"SO Status", type text}, {"Item by PAR Exp", type text}, {"Assigned?2", type text}, {"Doc Workflow", type text}, {"WF Flag", type text}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type",{{"Work In Progress Date Needed", type date}}),
    #"Sorted Rows1" = Table.Sort(#"Changed Type2",{{"Work In Progress Date Needed", Order.Ascending}}),
    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows1",{{"Sales Order Custom Fields Field1", "PAR Workflow"}, {"Sales Order Custom Fields Field7 (Stopped Billing Field)", "Stopped Billing Field"}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "Sales Order Detail Item Group", "Sales Order Detail Item Group - Copy"),
    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Sales Order Detail Item Group - Copy", "Product"}, {"Sales Order Custom Fields Field18", "Invoice Date of Service"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"Sales Order Number", "Sales Order Status", "Sales Order Manual Stop Reason", "Sales Order Manual Hold Reason", "Sales Order Custom Fields Field9", "Stopped Billing Field", "Invoice Date of Service", "PAR Workflow", "Sales Order Stop Type", "Work In Progress Assigned To", "Work In Progress Date Needed", "Place of Service Date of Discharge", "Patient State", "Ordering Doctor Doc NPI", "Insurance Pri Payor", "Insurance Pri Policy #", "Sales Order Detail Item Group", "Days from Exp Date", "Region Mapping.Region", "Exp Date Grouping", "Days from NBD", "NBD Grouping ", "Auth Covers?", "ItemMapping", "DNC Connection.DNC/EMR Access?", "NO RETRO PAYER", "Fax Upload Date", "GoScripts", "Parachute", "SLA", "TZ", "Region Lead", "Priority", "File Arrangement", "WF Flag", "NC Medicaid", "WIPDate_ActionDate", "SouthEast Vent", "Product", "Sales Order Detail Next Period", "Work In Progress WIP State"}),
    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "File", each "Future PAR"),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Action", each ""),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Notes", each ""),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Status", each "ADJUST ALL INVOICES"),
    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "Zero Balance", each ""),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom4",{"Sales Order Number", "Sales Order Status", "Sales Order Manual Stop Reason", "Sales Order Manual Hold Reason", "PAR Workflow", "Stopped Billing Field", "Sales Order Stop Type", "Work In Progress WIP State", "Work In Progress Assigned To", "Work In Progress Date Needed", "Patient State", "Ordering Doctor Doc NPI", "Insurance Pri Payor", "Insurance Pri Policy #", "Product", "Days from Exp Date", "Region Mapping.Region", "Exp Date Grouping", "Days from NBD", "Auth Covers?", "ItemMapping", "NO RETRO PAYER", "GoScripts", "Parachute", "SLA", "TZ", "Region Lead", "Priority", "File Arrangement", "File", "WF Flag"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Work In Progress Date Needed", type date}}),
    #"Sorted Rows" = Table.Sort(#"Changed Type1",{{"Work In Progress Date Needed", Order.Ascending}, {"Days from Exp Date", Order.Ascending}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Sorted Rows",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "Work In Progress Date Needed", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Work In Progress Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Product", "Work In Progress WIP State", "File Arrangement", "Sales Order Status", "Sales Order Manual Stop Reason", "Sales Order Manual Hold Reason", "Stopped Billing Field", "Sales Order Stop Type", "Days from Exp Date", "Exp Date Grouping", "Days from NBD", "Auth Covers?", "ItemMapping"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns1",{"Product", "File Arrangement",  "Days from Exp Date", "Exp Date Grouping", "Auth Covers?", "ItemMapping"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"Sales Order Number"}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Duplicates",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "Work In Progress Date Needed", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Work In Progress Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Sales Order Status", "Days from NBD", "Stopped Billing Field"}),
    #"Added Custom5" = Table.AddColumn(#"Reordered Columns2", "Assigned To", each ""),
    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Stop Aging", each ""),
    #"Reordered Columns3" = Table.ReorderColumns(#"Added Custom6",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "Work In Progress Date Needed", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Sales Order Status", "Days from NBD", "Stopped Billing Field", "Stop Aging", "Work In Progress Assigned To", "Sales Order Manual Stop Reason", "SouthEast Vent", "NBD Grouping "}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Reordered Columns3",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "Work In Progress Date Needed", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Sales Order Status", "Days from NBD", "Stopped Billing Field", "Stop Aging", "Work In Progress Assigned To", "Sales Order Manual Stop Reason",  "NBD Grouping ", "Fax Upload Date"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns4",{"SouthEast Vent"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Columns2",{{"WIPDate_ActionDate", type date}}),
    #"Reordered Columns5" = Table.ReorderColumns(#"Changed Type3",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "WIPDate_ActionDate", "Work In Progress Date Needed", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Sales Order Status", "Days from NBD", "Stopped Billing Field", "Stop Aging", "Work In Progress Assigned To", "Sales Order Manual Stop Reason", "NBD Grouping ", "Fax Upload Date"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns5",{"Work In Progress Date Needed"}),
    #"Reordered Columns6" = Table.ReorderColumns(#"Removed Columns3",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "WIPDate_ActionDate", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Sales Order Status", "Days from NBD", "Stopped Billing Field", "Stop Aging", "Work In Progress Assigned To", "Sales Order Manual Stop Reason", "Sales Order Manual Hold Reason", "Sales Order Stop Type", "NBD Grouping ", "Fax Upload Date"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Reordered Columns6",{"Sales Order Stop Type"}),
    #"Added Custom7" = Table.AddColumn(#"Removed Columns4", "CALLATTEMPT", each ""),
    #"Reordered Columns7" = Table.ReorderColumns(#"Added Custom7",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "WIPDate_ActionDate", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Sales Order Status", "Days from NBD", "Stopped Billing Field", "Stop Aging", "Work In Progress Assigned To", "Sales Order Manual Stop Reason", "Sales Order Manual Hold Reason", "CALLATTEMPT", "NBD Grouping ", "Fax Upload Date", "Sales Order Custom Fields Field9"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Reordered Columns7",{{"Sales Order Custom Fields Field9", type date}}),
    #"Reordered Columns8" = Table.ReorderColumns(#"Changed Type4",{"Sales Order Number", "Insurance Pri Payor", "Insurance Pri Policy #", "NO RETRO PAYER", "Sales Order Detail Item Group", "PAR Workflow", "File", "Ordering Doctor Doc NPI", "WIPDate_ActionDate", "DNC Connection.DNC/EMR Access?", "GoScripts", "Parachute", "WF Flag", "Assigned To", "Action", "Notes", "Status", "Priority", "Zero Balance", "Region Mapping.Region", "Region Lead", "NC Medicaid", "SLA", "Invoice Date of Service", "Patient State", "TZ", "Sales Order Status", "Days from NBD", "Stopped Billing Field", "Stop Aging", "Work In Progress Assigned To", "Sales Order Manual Stop Reason", "Sales Order Manual Hold Reason", "CALLATTEMPT", "NBD Grouping ", "Fax Upload Date", "Sales Order Custom Fields Field9", "Place of Service Date of Discharge", "Sales Order Detail Next Period", "Work In Progress WIP State"}),
    #"Changed Type5" = Table.TransformColumnTypes(#"Reordered Columns8",{{"Place of Service Date of Discharge", type date}})
in
    #"Changed Type5"