HELD Completes - Team Report

let
    Source = Excel.Workbook(File.Contents("C:\Users\Alodia Bendicio\Downloads\Team Report.xlsx"), null, true),
    #"Removed Other Columns" = Table.SelectColumns(Source,{"Name", "Data"}),
    #"1. FILTERED Team Report sheet" = Table.SelectRows(#"Removed Other Columns", each ([Name] <> "Team Report")),
    #"Expanded Data" = Table.ExpandTableColumn(#"1. FILTERED Team Report sheet", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34"}, {"Data.Column1", "Data.Column2", "Data.Column3", "Data.Column4", "Data.Column5", "Data.Column6", "Data.Column7", "Data.Column8", "Data.Column9", "Data.Column10", "Data.Column11", "Data.Column12", "Data.Column13", "Data.Column14", "Data.Column15", "Data.Column16", "Data.Column17", "Data.Column18", "Data.Column19", "Data.Column20", "Data.Column21", "Data.Column22", "Data.Column23", "Data.Column24", "Data.Column25", "Data.Column26", "Data.Column27", "Data.Column28", "Data.Column29", "Data.Column30", "Data.Column31", "Data.Column32", "Data.Column33", "Data.Column34"}),
    #"2. RENAMED cols" = Table.RenameColumns(#"Expanded Data",{{"Name", "Team"}, {"Data.Column1", "Agent"}, {"Data.Column2", "Agent Email"}, {"Data.Column3", "Calls"}, {"Data.Column4", "Calls/Hr"}, {"Data.Column5", "Talk"}, {"Data.Column6", "Wrap Up"}, {"Data.Column7", "Conv"}, {"Data.Column8", "Conv %"}, {"Data.Column9", "Conv/Hr"}, {"Data.Column10", "Points"}, {"Data.Column11", "Points/Hr"}, {"Data.Column12", "Logged In"}, {"Data.Column13", "Eff %"}, {"Data.Column14", "AAT"}, {"Data.Column15", "AHT"}, {"Data.Column16", "ATT"}, {"Data.Column17", "AWT"}, {"Data.Column18", "Administrative"}, {"Data.Column19", "Break"}, {"Data.Column20", "Coaching"}, {"Data.Column21", "Unavailable"}, {"Data.Column22", "QA Score"}, {"Data.Column23", "Scorecards"}, {"Data.Column24", "Passed"}, {"Data.Column25", "Auto Fails"}, {"Data.Column26", "Holds"}, {"Data.Column27", "Hold"}, {"Data.Column28", "Hold/Call"}, {"Data.Column29", "Rings Tot"}, {"Data.Column30", "Rings Ans"}, {"Data.Column31", "Rings Decl"},  {"Data.Column32", "Rings Timeout"},  {"Data.Column33", "Rings Miss"}, {"Data.Column34", "Rings Aban"}}),
    #"3. ADDED Filter col" = Table.AddColumn(#"2. RENAMED cols", "Filter Column", each if [Agent] = [Team] then true else if [Agent] = "Agent" then true else if [Agent] = "Team Total" then true else if [Agent] = null then true else false),
    #"4. FILTERED TRUE" = Table.SelectRows(#"3. ADDED Filter col", each ([Filter Column] = false)),
    #"5. REMOVED Filter col" = Table.RemoveColumns(#"4. FILTERED TRUE",{"Filter Column"}),
    #"6. ADDED TeamName col" = Table.AddColumn(#"5. REMOVED Filter col", "TeamName", each if Text.Contains([Team], "AH-SnapHeld-FTP-Prod") then "Y" else if Text.Contains([Team], "AH-AeroHeld-FTP-Prod") then "Y" else if Text.Contains([Team], "AH-SnapHeld-Benver-Prod") then "Y" else if Text.Contains([Team], "AH-AeroHeld-Benver-Prod") then "Y" else if Text.Contains([Team], "HBOSS BT Project-Blank Held") then "Y" else if Text.Contains([Team], "CDT,AddDoctor,GS Escal") then "Y" else if Text.Contains([Team], "AH-SnapHeld-CS-Prod") then "Y" else if Text.Contains([Team], "AH-AeroHeld-CS-Prod") then "Y" else if Text.Contains([Team], "AH-SnapHeld-DM-Prod") then "Y" else if Text.Contains([Team], "AH-AeroHeld-DM-Prod") then "Y" else if Text.Contains([Team], "AH-SNAPHELD-FM-PROD") then "Y" else if Text.Contains([Team], "Diab FM") then "Y" else if Text.Contains([Team], "AH DiabeticHeld-FaxMap-prod") then "Y" else if Text.Contains([Team], "AH-AeroHeld-FM-Prod") then "Y" else if Text.Contains([Team], "AH-SnapHeld-FaxRes-Prod") then "Y" else if Text.Contains([Team], "AH-SnapHeld-FaxRev-Prod") then "Y" else if Text.Contains([Team], "HBOSS BT Project-No Mask Revie") then "Y" else if Text.Contains([Team], "Tricare East RX Review") then "Y" else if Text.Contains([Team], "HBOSS BT Project - UHC") then "Y" else if Text.Contains([Team], "VA MEDICAID HELD") then "Y" else if Text.Contains([Team], "AH SNAPHELD - SP Team") then "Y" else "NA"),
    #"7. FILTERED TeamName col" = Table.SelectRows(#"6. ADDED TeamName col", each ([TeamName] = "Y")),
    #"8. REMOVED TeamName col" = Table.RemoveColumns(#"7. FILTERED TeamName col",{"TeamName"})
in
    #"8. REMOVED TeamName col"